spring:
  jpa:
    database: mysql
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/renren_security?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
  thymeleaf:
    mode: HTML5
    cache: false
    encoding: UTF-8

server:
  port: 8088